BUTTON1: "Latte"
DESCRIPTION1: "купити каву"
BUTTON2: "Terms and Conditions"
DESCRIPTION2: "Загальні положення та умови"
BUTTON3: "Help"
DESCRIPTION3: "потрібна допомога?"
BUTTON4: "Instruction"
DESCRIPTION4: "як купити товар?"
CONTACT_REQUEST: "Щоб скористатися сервісом, будь ласка, передайте свій номер телефону. Ручне введення номеру недоступне в цілях безпеки 👇"
LOCATION_REQUEST: "Щоб скористатися сервісом, будь ласка, передайте своє місцезнаходження. Ручне введення недоступне в цілях безпеки 👇"
TEST_CARD_PORTMONE: "4444 3333 2222 1111"
TEST_CARD_LIQPAY: "4242 4242 4242 4242"
TEST_CARD_STRIPE: "4242 4242 4242 4242"
SUPPORT: "092 236 43 36"
PRODUCT: "Latte"
PRODUCT_desc: "Лате немов створений спеціально для побачень – так гармонійно переплітаються у ньому гіркуваті й солодкі нотки, такий прекрасний і повітряний вигляд він має у прозорому склі, такий ніжний у нього смак і такий підбадьорливий ефект"