version: '3'
services:
  app:
    image: flask_pay
    environment:
      - DATABASE_URL=postgresql://postgres:my_love1982@localhost:5432/bot_users
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Ensure the .env file is included in the volum